# Comment
FROM gcr.io/distroless/static-debian13:debug-nonroot@sha256:dafe405d2cd55f5d5abaa0fabfa90cff628ec7091f2a3da9389fcfe4d876a7ce AS stage1

# Comment
FROM gcr.io/distroless/base-nossl-debian13:debug-nonroot@sha256:b455d83ad39da5b4fb5ed34bf6b45daaa23fe02cb76ebb96af44c407cadf4e23 AS stage2